version: 2

project_name: altcha
builds:
  - id: altcha
    main: ./cmd/altcha
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.ProjectVersion={{.Version}} -X main.GitRef={{.ShortCommit}} -X main.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
